config/routes.rb
MCalendare::Application.routes.draw do

  resources :events

end

app/models/event.rb
class EventDay
  attr_accessor :day, :description, :event_id
end

class Event < ActiveRecord::Base
  attr_accessible :day_of_mounth, :day1, :day2, :day3, :day4, :day5, :day6, :day7, :day_of_week, :description, :end_date, :start_date

  def self.date_event(some_date)
    if some_date.class != Date
      return
    end
    m_day = some_date.day ||= "NULL"
    w_day = some_date.days_to_week_start ||= "NULL"
    #querty_text = "day_of_mounth = ? AND day_of_week = ? "
    Event.where("day_of_mounth = ? AND day_of_week = ? AND start_date <= ?", m_day, w_day, some_date)
  end

  def self.get_active_events(on_date)
    Event.where("start_date <= ? AND (end_date >= ? OR end_date IS NULL)", on_date, on_date)
  end

  def date(date_of_month)
    beginninig_date = date_of_month.beginning_of_month
    end_date        = date_of_month.end_of_month
    days_of_event = []
    for cur_day in beginninig_date..end_date
      cur_date = Date.new(date_of_month.year, date_of_month.month, cur_day)
      if self.day_of_mounth == cur_day
        days_of_event.push(EventDay.new(:day => cur_date, :description => self.description, :event_id => self))
      elsif self.day_of_week == cur_date.days_to_week_start + 1
        days_of_event.push(cur_date)
      end
    end
    return days_of_event
  end

  def in_day_of_week(weeks_day)
    # ans = false
    # case (weeks_day)
    #   when 1 then ans = true if self.day1 != 0
    #   when 2 then ans = true if self.day2 != 0
    #   when 3 then ans = true if self.day3 != 0
    #   when 4 then ans = true if self.day4 != 0
    #   when 5 then ans = true if self.day5 != 0
    #   when 6 then ans = true if self.day6 != 0
    #   when 7 then ans = true if self.day7 != 0
    # end
    #return ((weeks_day > 0) and (weeks_day < 8)) if self["day#{weeks_day}"] != 0
    return self["day#{weeks_day}"] != 0
  end

  def self.events_days(beginninig_date, end_date)
    events = Event.get_active_events(beginninig_date)
    events_days = []
    for event in events do
      for cur_day in beginninig_date..end_date
        #puts "Year #{beginninig_date.year} - #{beginninig_date.month} - #{cur_day}"
        #cur_date = Date.new(beginninig_date.year, beginninig_date.month, cur_day)
        if (event.day_of_mounth == cur_day.day) or event.in_day_of_week(cur_day.days_to_week_start + 1)
          #events_days.push(EventDay.new(:day => cur_day, :description => event.description, :event_id => event))
          ev1 = EventDay.new #(:day => cur_day, :description => event.description, :event_id => event)
          ev1.day = cur_day
          ev1.description = event.description
          ev1.event_id = event
          events_days.push(ev1)
        end
      end
    end
    return events_days
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @type_period = params[:type_period].to_i ||= 0 # 0 - month, 1- week, 2 -day
    if @type_period == 0
      @date = params[:month] ? Date.parse(params[:month]) : Date.today
      per = "month"
    elsif @type_period == 1
      @date = params[:week] ? Date.parse(params[:week]) : Date.today
      per = "week"
    elsif @type_period == 2
      @date = params[:day] ? Date.parse(params[:day]) : Date.today
      per = "day"
    end
    if @type_period == 2
      start_val = @date
      end_val   = @date
    else
      start_val = @date.method("beginning_of_#{per}").call
      end_val = @date.method("end_of_#{per}").call
    end
    @events = Event.events_days( start_val, end_val )
  end

  def create
    @event = Event.new(params[:event])

    if @event.save
      flash[:success] = "OK"
      redirect_to events_path
    else
      flash[:error] = "ERORR"
      redirect_to :new
    end
  end


  

  def new
    @event = Event.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_controller_helper.rb
module EventsControllerHelper
end

app/views/events/_fields.html.erb
  <div class="field">
    <%= f.label :description, "Description:" %><br />
    <%= f.text_field :description %>
  </div> 

   <div class="field">
    <%= f.label :day_of_mounth, "Day of month:" %><br />
    <%= f.text_field :day_of_mounth %>
  </div> 

   <div class="field">
    <%= f.label :start_date, "Start date:" %><br />
    <%= f.text_field :start_date, :class => "datepicker" %>
  </div>

  <div class="field">
    <%= f.label :end_date, "End date:" %><br />
    <%= f.text_field :end_date %>
  </div>  

  <div class="field">
    <%= f.label :day1, "Mounday:" %><br />
    <%= f.check_box :day1 %>
  </div> 

<div class="field">
    <%= f.label :day2, "Tuesday:" %><br />
    <%= f.check_box :day2 %>
  </div> 

<div class="field">
    <%= f.label :day3, "Wednesday:" %><br />
    <%= f.check_box :day3 %>
  </div> 

  <div class="field">
    <%= f.label :day4, ":Thursday" %><br />
    <%= f.check_box :day4 %>
  </div> 

  <div class="field">
    <%= f.label :day5, "Friday:" %><br />
    <%= f.check_box :day5 %>
  </div> 

  <div class="field">
    <%= f.label :day6, "Saturday:" %><br />
    <%= f.check_box :day6 %>
  </div> 

  <div class="field">
    <%= f.label :day7, "Sunday:" %><br />
    <%= f.check_box :day7 %>
  </div> 

app/views/events/_form.html.erb
<%= f.text_field :description %>

app/views/events/index.html.erb
<%= link_to "Add event", new_event_path %>
<%= form_tag(events_path, :method => "get") do %>
  <%= label_tag(:q, "Period type:") %>
  <%= select_tag :type_period, options_for_select([["month", 0], ["week", 1], ["day", 2]]) %>
  <br><%= submit_tag("Change") %>
<% end %>
<div id="calendar">
  <h2 id="month">
    <% if @type_period == 0 %>
      <%= link_to "<", :month => (@date.beginning_of_month-1).strftime("%Y-%m-%d") %>
    <% elsif @type_period == 1 %>
      <%= link_to "<", {:week => (@date.beginning_of_week-1).strftime("%Y-%m-%d"), :type_period => 1}  %>
    <% elsif @type_period == 2 %>
      <%= link_to "<", {:day => (@date.beginning_of_day-1).strftime("%Y-%m-%d"), :type_period => 2} %>
    <% end %>
    <%=h @date.strftime("%B %Y") if @type_period == 0%>
    <%=h @date.strftime("%W %Y") if @type_period == 1%>
    <%=h @date.strftime("%D") if @type_period == 2%>
    <% if @type_period == 0 %>
      <%= link_to ">", :month => (@date.end_of_month+1).strftime("%Y-%m-%d") %>
    <% elsif @type_period == 1 %>
      <%= link_to ">", {:week => (@date.end_of_week+1).strftime("%Y-%m-%d"), :type_period => 1} %>
    <% elsif @type_period == 2 %>
      <%= link_to ">", {:day => (@date.end_of_day+1).strftime("%Y-%m-%d"),  :type_period => 2} %>
    <% end %>
  </h2>
  <%= debug(@type_period)  %>
  
  <%= table_for(@events) do |t| %> 
    <%= t.body do |front_man| %>
      <%= t.r do %>
        <%= t.d(h(front_man.day)) %>
        <%= t.d(h(front_man.description)) %>
      <% end %>
    <% end %>
  <% end %>

  <% calendar_for @events, :year => @date.year, :month => @date.month do |calendar| %>
    <%= debug(@date)  %>
    <%= debug(@events)  %>
    <%= calendar.head('Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday') %>
    <% calendar.day(:day_method => :day) do |date, events| %>
      <%= date.day %>
      <ul>
        <% if events.nil? %>
          <%= date.cweek %>
        <% else %>
          <% for event in events %>
            <li>event.description</li>
          <% end %>
        <% end %>
      </ul>
    <% end %>
  <% end %>
</div>

app/views/events/new.html.erb
<h1>Add event:</h1>
<%= form_for(@event) do |f| %>
  <%= render 'fields', :f => f %>
  <div class="actions">
    <%= f.submit "Add" %>
  </div>
<% end %>
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MCalendare</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>

  


  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<%= debug(params) %>
</body>
</html>